
name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create SSH key file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa


    - name: Copy files to EC2
      #uses: appleboy/scp-action@v0.1.4
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}      # github secrets에 EC2_HOST를 저장해야 함
        username: ${{ secrets.EC2_USER }}  # github secrets에 EC2_USER를 저장해야 함
        key: ${{ secrets.EC2_SSH_KEY }}    # github secrets에 EC2_SSH_KEY를 저장해야 함
        source: "."    # 현재 디렉토리의 모든 파일을 복사
        target: "/home/ubuntu/raw_sql"

    - name: SSH into EC2 and run Docker Compose 
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }} 
        script: |
          cd raw_sql
          docker-compose down
          docker-compose up -d --build
